[default.extend-words]
dcat = "dcat"
demoncat = "demoncat"
npu = "npu"
qdisc = "qdisc"
netem = "netem"
tbf = "tbf"
hccn = "hccn"
roce = "roce"
dscp = "dscp"
mtu = "mtu"
ethtool = "ethtool"
iproute = "iproute"
systemctl = "systemctl"
taskset = "taskset"
sidecar = "sidecar"
netdetect = "netdetect"
davinci = "davinci"
cjson = "cjson"
ascend = "ascend"
pn = "pn"
optin = "optin"
ser = "ser"
nd = "nd"
clen = "clen"
pathc = "pathc"
